### ISSUE TITLE
Better docs navigation

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#143]
All docs are stored in one `README.md` which makes navigation tricky. It'd become even worse once we implement different interfaces (e.g., webpack, rollup, CLI). 

Possible solutions:

- Generate a table of contents and append it to `README.md`
- Use Github wiki
- Use Github pages (+ Jekyll?)

Also, it'd be good if the docs for the currently published version of `htmlnano` are shown by default (not the `master` branch) to avoid confusion when some feature is implemented but not published to _npm_ yet.

**Comment by maltsev** [comment]
I decided to use docusaurus + Netlify. @Scrum can you please approve Netlify access to the posthtml org?

**Comment by Scrum** [comment]
> I decided to use docusaurus + Netlify. @Scrum can you please approve Netlify access to the posthtml org?

done

**Comment by maltsev** [comment]
Done: https://htmlnano.netlify.app

**Comment by maltsev** [comment]
@Scrum can you please set it as the repo website?

**Comment by Scrum** [comment]
> @Scrum can you please set it as the repo website?

done
