### ISSUE TITLE
Redundant whitespace not removed

### ISSUE THREAD

**Issue by thewilkybarkid** [posthtml/htmlnano#145]
When using `collapseWhitespace: aggressive`, the following remains unchanged:

```html
before <a href="#link"> <i>after</i></a>
```

The space inside the `<a>` can be removed as it collapses into the one outside.

**Comment by SukkaW** [comment]
@thewilkybarkid 

The current implementation is both spaces around `<a>` and spaces inside `</a>` should be retained, thus causing redundancy.

I am refactoring the module to avoid this edge case.
