### ISSUE TITLE
Whitespace within conditional comments is being collapsed

### ISSUE THREAD

**Issue by devinus** [posthtml/htmlnano#15]

**Comment by devinus** [comment]
Actually, this seems like good behavior. But I do need a way to not strip some HTML comments. Using triple dash HTML comments has some prior art in Pandoc.

E.g.

`<!--- do not strip or collapse whitespace -->`

I'll do a PR for this.

**Comment by maltsev** [comment]
I don't think this is a good behavior. The module `collapseWhitespace` shouldn't treat comments at all. And the module `removeComments` should either remove the comment or keep it unalterable.

I agree with you about the prior comments and triple dash syntax. It'd awesome if you'll do a PR for that.

**Comment by devinus** [comment]
Well, things inside conditional comments are usually (always?) HTML, so it would be nice to minify that too.

**Comment by maltsev** [comment]
Ah, I'm sorry. I was talking about comments in general. Yes, you're right. But I think it'll be better to have a separate module for that, which will parse HTML inside the conditional comment and minify it with the appropriate modules (`collapseWhitespaces, minifyCss, minifyJs, etc`).

**Comment by maltsev** [comment]
So I've created two issues for that:
- [Minify content inside conditional comments](https://github.com/maltsev/htmlnano/issues/16)
- [Don't alter regular HTML comments inside modules](https://github.com/maltsev/htmlnano/issues/17)

**Comment by SukkaW** [comment]
Since both https://github.com/maltsev/htmlnano/issues/16 and https://github.com/maltsev/htmlnano/issues/17 has been fixed, IMHO it is ok to close the issue now.
