### ISSUE TITLE
[Proposal] Replace UnCSS with fork

### ISSUE THREAD

**Issue by NovaAtWarren** [posthtml/htmlnano#152]
I've created a fork of UnCSS to try and update some of the insecure dependencies, and to merge some PRs, as the original collaborators seem to not be performing said task.
As UnCSS (the version referenced by package.json) is unmaintained, and my fork is maintained, it may be a good idea to switch to decrease dependency on outdated packages.
I can make a PR if you desire.

**Comment by maltsev** [comment]
@NovaAtWarren I appreciate that you forked uncss and upgraded it! But let me be honest with you, I'm hesitant to replace the original uncss with a forked version that is not actively used by other people and which future is also unclear (e.g., will it be maintained in the future, etc).

I'm not that familiar with the advanced features of npm, but maybe there is a way to replace uncss with your forked version on a per-project basis (`peerDependencies`?). Then I could mention your fork in the readme, so if people want they can use uncss.

I'm also open to other solutions!

**Comment by NovaAtWarren** [comment]
I can understand your hesitation entirely.
In this case, maybe a .patch and a small section in the readme, stating what it updates and why you might like it?

**Comment by maltsev** [comment]
> In this case, maybe a .patch and a small section in the readme, stating what it updates and why you might like it?

Sure. Sounds good to me! Would you provide it, please?

> Additional idea, a forked-uncss branch

Sorry, I'm not quite sure how this would work. But, I think, it also sounds good to me!

**Comment by NovaAtWarren** [comment]
> Sure. Sounds good to me! Would you provide it, please?

Sorry if I implied you'd make the patch, I do intend on writing it myself.

> Sorry, I'm not quite sure how this would work. But, I think, it also sounds good to me!

What I was thinking with that was making a new branch on this repo, and applying the patch to that branch. Uploading that branch to NPM whenever `package.json` > `version` is updated or pushing manually, and having me make PRs from main to the branch to keep it updated.
Now that I've slept on it, though, I'm not _as_ sure it's a good idea.

I'll get working on the patch

**Comment by maltsev** [comment]
Thanks a lot!
