### ISSUE TITLE
Minify content inside conditional comments

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#16]
Source:

``` html
<!--[if lte IE 7]>
<style type="text/css">
.title {
  color: red;
}
</style>
<![endif]-->
```

Minified:

``` html
<!--[if lte IE 7]><style>.title {color:red}</style><![endif]-->
```

The module should parse the content inside a conditional comment and minify it with `htmlnano`.

**Comment by SukkaW** [comment]
It is a bit hard to implement the feature. posthtml parse conditional comments as normal comments (which will be interpreted as `string`, not a `tree`). See also https://github.com/posthtml/posthtml-parser/issues/9

**Comment by maltsev** [comment]
What if after initial parsing we strip the conditional comment tags and parse the conditional comment content again with PostHTML? Then we could apply all modifications again.

**Comment by SukkaW** [comment]
> What if after initial parsing we strip the conditional comment tags and parse the conditional comment content again with PostHTML? Then we could apply all modifications again.

Then we will have to deal with unfulfilled Promise inside the posthtml tree. `tree.walk` and `tree.match` is not designed to be work with Promise in the first place.
