### ISSUE TITLE
Remove uncss?

### ISSUE THREAD

**Issue by devongovett** [posthtml/htmlnano#165]
It seems pretty much unmaintained, and purgecss is already supported as an alternative. Currently, the dependency on uncss causes a bunch of deprecated packages to be installed via a very old JSDOM dependency, including request, request-promise-native, and har-validator. These show up during an npm install of htmlnano or any other tool using htmlnano (like Parcel).

**Comment by SukkaW** [comment]
@maltsev 

What about making them peer dependencies? Anyone who wants to use will have to install it by him/herself.

**Comment by maltsev** [comment]
> What about making them peer dependencies? Anyone who wants to use will have to install it by him/herself.

Yes, that's a great idea! I'm not 100% sure it'd work seamlessly though. It'd be awesome if someone could create a PR with that :-)

**Comment by maltsev** [comment]
Fixed in #168.

**Comment by devongovett** [comment]
This is now causing a security issue for all downstream dependencies of htmlnano due to an old version of postcss. See https://github.com/advisories/GHSA-566m-qj78-rww5. Any chance this could be released?

**Comment by maltsev** [comment]
> Any chance this could be released?

Sure. I'll do it this evening.

**Comment by maltsev** [comment]
Done: https://www.npmjs.com/package/htmlnano/v/2.0.0

**Comment by folknor** [comment]
But uncss is still used in `lib/modules/removeUnusedCss.es6`? What is it I don't understand?
It's also listed in package.json and my build system is still complaining about uncss 0.17.3 depending on old, unmaintainted, unsupported, and explicitly deprecated package versions.
