### ISSUE TITLE
Can we switch off the warning if I'm not using `minifyJs`, please?

### ISSUE THREAD

**Issue by frederikhors** [posthtml/htmlnano#175]
In my console I'm having this warning:

`You have to install "terser" in order to use htmlnano's "minifyJs" module`.

I'm not using `minifyJs`. I'm only using htmlnano like this:

```js
posthtml([htmlnano()])
```

Can we switch off the warning if I'm not using `minifyJs`, please?

**Comment by maltsev** [comment]
> I'm not using minifyJs. I'm only using htmlnano like this:

By default, `htmlnano` loads with the `safe` preset which has `minifyJs` enabled. You can disable it if you don't need it:

```js
posthtml([htmlnano({
    minifyJs: false,
})])
```
