### ISSUE TITLE
Crash with JSON-LD data

### ISSUE THREAD

**Issue by AndrewKvalheim** [posthtml/htmlnano#182]
htmlnano 2.0.1 crashes when processing JSON-LD data:

```console
$ yarn add htmlnano@2.0.1
$ node --eval "require('htmlnano').process('<script type=application/ld+json>{}</script>')"
…/node_modules/htmlnano/lib/modules/removeComments.js:34
    return contents.filter(content => !isCommentToRemove(content, removeType));
                    ^

TypeError: contents.filter is not a function
    at …/node_modules/htmlnano/lib/modules/removeComments.js:34:21
    at …/node_modules/htmlnano/lib/htmlnano.js:139:28
    at traverse (…/node_modules/posthtml/lib/api.js:105:26)
    at Array.walk (…/node_modules/posthtml/lib/api.js:39:10)
    at …/node_modules/htmlnano/lib/htmlnano.js:122:12
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I’ve used empty data here for brevity but this also happens with ordinary Schema.org content.

**Comment by mischnic** [comment]
Also appears to happen with SVG: https://github.com/parcel-bundler/parcel/issues/7906

**Comment by maltsev** [comment]
Sorry about the bug!

I deprecated this new version. Please use 2.0.0 for the time being until the bug is fixed.

@SukkaW is it something you can fix?

**Comment by SukkaW** [comment]
> Sorry about the bug!
> 
> I deprecated this new version. Please use 2.0.0 for the time being until the bug is fixed.
> 
> @SukkaW is it something you can fix?

I will work on it ASAP. Don't know why the change passes our unit tests though.

**Comment by dannya** [comment]
@maltsev please can you update the GitHub releases too, it still shows 2.0.1 as the latest.

**Comment by SukkaW** [comment]
@dannya 2.0.2 is released on npm and includes the fix.

**Comment by dannya** [comment]
@SukkaW sure, so might as well update the GitHub release too!

![image](https://user-images.githubusercontent.com/394687/187977587-22607e30-a5e3-4144-aa20-da8ffd9206cc.png)
