### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by metonym** [posthtml/htmlnano#201]
It would be useful to have TypeScript definitions when using the library programmatically with Node/TypeScript.

Would you be receptive to a PR that adds types? As an alternative, I'd be happy to contribute them to https://github.com/DefinitelyTyped/DefinitelyTyped as `@types/htmlnano` if it's beyond the scope of this project.

**Comment by maltsev** [comment]
Yes, I'd be happy to accept your PR. Thanks!
