### ISSUE TITLE
[fix]: [collapseWhitespace] Normalize white spaces safely

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#21]
> Using \s to normalize HTML whitespace will strip out characters that are actually rendered by a web browser. Such would be classified as a lossy change and would produce a different visual result. 
> https://www.npmjs.com/package/normalize-html-whitespace

@stevenvachon, thanks for the idea.

**Comment by stevenvachon** [comment]
Along with this, whitespace between tags within `<head>` (except for `<title>`) can be completely removed as the entire element is not rendered.

**Comment by maltsev** [comment]
@stevenvachon, thanks! I've created an issue for that: #24

**Comment by bfred-it** [comment]
I think this is fixed (at least partially) by setting `collapseWhitespace: 'conservative'`. I saw `the <em>space</em>` before/after `em` being removed and that option avoids that.

**Comment by stevenvachon** [comment]
I haven't researched how web browsers render spaces across different elements. I think that it changes depending on block/inline level, which can be overridden via CSS. It might be safer to simply reduce multiple spaces to single spaces via the above mentioned library.

**Comment by bfred-it** [comment]
Exactly. Ignore I set two `div` to `display: inline` the space will matter

**Comment by stevenvachon** [comment]
Ok. As originally stated, though, the "conservative" `/s+` is not the same as the above mentioned library.

Also, I think that the default should not be "all", since it results in unexpected render differences.

**Comment by maltsev** [comment]
Done. It'll be released in 0.2.0 version (I think next week).

**Comment by maltsev** [comment]
Released: [0.2.0](https://github.com/posthtml/htmlnano/releases/tag/0.2.0).
