### ISSUE TITLE
Smart encapsulation

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#27]
@stevenvachon:

> switch between ' and " (per attribute) as attribute value encapsulators to find which produces the smallest output (due to any necessary commenting: attr='blah \'blah\'' vs attr="blah 'blah'")

**Comment by wooorm** [comment]
[Here’s what I settled for](https://github.com/syntax-tree/hast-util-to-html/blob/93a30492df8de8ec4ad25908737e0c4ce6437b0a/lib/element.js#L203-L228).

**Comment by kevincox** [comment]
I wouldn't be surprised if this actually raised the gzip size on average. Unless you have a large number of strings with only one type of quote consistently probably gives you the smallest result after compression.

**Comment by maltsev** [comment]
@kevincox very good point! We should test that before starting to implement that minification.

**Comment by SukkaW** [comment]
The feature has been implemented in https://github.com/posthtml/posthtml-render/pull/47 so the issue could be closed now.
