### ISSUE TITLE
Move to it's own Organisation (htmlnano)

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/htmlnano#32]
👋 

There are plenty of Issues with `help-wanted`  label and I'm eager to help out. Beforehand I would like to discuss an eventual move of this module and gulp-htmlnano to it's own [org](https://github.com/orgs/htmlnano) (Just for preserving the name atm, will be your ownership of course :) ). If you don't like the idea, please give my some insight of your prefered way to collaborate here. 

#### Why

- indicates seriousity
- better community building
- better collaboration options
- removes the impression of being a 'one-man' show, maybe hard to justify corporate usage for some folks

#### Structure

- htmlnano-cli (@me)
- htmlnano
- gulp-htmlnano
- grunt-htmlnano (@me)
- maybe move all kinds of minifications to their own posthtml-plugins (but secondary and discussable :), then chore done by @me aswell)

**Comment by maltsev** [comment]
Hi @michael-ciniawsky,

First of all, thank you for your helping! I think it'd be overhead to create a separate organization for this module. Let's move it to [posthtml](https://github.com/posthtml) instead. What do you think?

> maybe move all kinds of minifications to their own posthtml-plugins

Steven already proposed that in #12. But I still think it would be overhead. For me It's better to have all those minification in one place (both from UX and maintainability perspective). Though, I'm open to a discussion.

**Comment by michael-ciniawsky** [comment]
> First of all, thank you for your helping! I think it'd be overhead to create a separate organization for this module. Let's move it to posthtml instead. What do you think?

Since minifiers and linters are always kind of 'outstanding' projects ;), the question is, does a separate org (place) makes more sense. Initially I was thinking of PostHTML aswell, but there are many other repos (noise). Sure it's build on top of posthtml, but you can use it without even knowing what the heck posthtml is aswell ;). My experience is that people somehow always appreciate it when there is a clear chrome around a certain 'topic'. But I'm fine with both :)

e.g In the near future, I will ask dev's @htmllint (htmlparser2), if they are basically open to/ interested in migrating/joining forces with @posthtml, but htmllint, or if rejected {{ name }}, should 'shine' on its own ✨ . Invite to @posthtml-collaborators and bam! 😛 

> Steven already proposed that in #12. But I still think it would be overhead. For me It's better to have all those minification in one place (both from UX and maintainability perspective). Though, I'm open to a discussion.

Yep, mention was based on this issue :), you're right it's overhead and also unlikely many folks will really want to build their own 'partial minifiers' ;). Discarded for now I guess 😛

**Comment by michael-ciniawsky** [comment]
@maltsev Did I scare you off a bit with my tendency PR/marketing bubbling 😛 ?

**Comment by maltsev** [comment]
@michael-ciniawsky no, not at all :-) Sorry, I was just busy these few days. 

I don't think that users (i.e. these who just use the library without participating in development) care about that at all. I think it's more about the community of people who help to develop the library. And in my opinion, it's better to build one community around PostHTML than two (PostHTML + htmlnano) because they'd be very similar. So if you don't mind I'll move htmlnano and related repositories to posthtml namespace. Does this sound good to you?

**Comment by michael-ciniawsky** [comment]
👍 I'm perfectly fine with it, maybe the plugins catalog aswell then 😛 .Proper Website and Plugins Catalog (in terms of conjunction of those two, current catalog is awesome on it's own) is the next bigger TODO on the list :). kk when you find the time :shipit: . I will comment on or file issues then for getting started 😊

**Comment by maltsev** [comment]
Great! I'll transfer it on the weekend.

**Comment by michael-ciniawsky** [comment]
👍

**Comment by maltsev** [comment]
I've transferred both _htmlnano_ and _gulp-htmlnano_ repositories. @michael-ciniawsky I guess, we could close this issue?

**Comment by michael-ciniawsky** [comment]
@maltsev yep 😛 👍

**Comment by michael-ciniawsky** [comment]
Ok, if I update the README style like e.g [posthtml-expressions](https://github.com/posthtml/posthtml-expressions) leaving all contents, for getting started ? 💯
