### ISSUE TITLE
Minify srcset values

### ISSUE THREAD

**Issue by stevenvachon** [posthtml/htmlnano#38]
```html
<img srcset="image.png 1x, image2.png 2x">
<img srcset=" ">
```
can be shortened to:
```html
<img srcset="image.png,image2.png 2x">
<img>
```

[parse-srcset](https://npmjs.com/parse-srcset)

**Comment by SukkaW** [comment]
IMHO, the issue could be closed by now.

Strip spaces between image candidates will result in a **definitely invalid** srcset and might not be tolerated by browsers, while minify srcset with `minifyURLs` has been implemented in #117.
