### ISSUE TITLE
Published patch for recent PR

### ISSUE THREAD

**Issue by selbyk** [posthtml/htmlnano#43]
I would like to request a patch be published whenever you get a chance.

And for the future for quick iterations--is there a simple way to include unreleased htmlnano in a project? I'm currently trying `"htmlnano": "github:Rebelmail/htmlnano#rebel"` in our `package.json` with yarn.  The branch is the PR I made with the compiled files committed.  It works--the first time installed with no yarn.lock and then subsequent installs (or adding new packages) seems to remove the compiled files.  I'm going to try converting back to npm to see if it works as desired, but do you know of any other approaches (besides a private repo or publishing)?

**Comment by maltsev** [comment]
I published the new version: https://www.npmjs.com/package/htmlnano

Sorry, I don't know how to include an unreleased package. If you'll find a solution it'll be nice if you post it here :-)

**Comment by selbyk** [comment]
Thanks for the quick reply.  Alls well now, I don't even remember this PR.
