### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by stevenvachon** [posthtml/htmlnano#44]
It's meant for apps, not published packages. They are automatically npmignored which means that while users of the project will install whatever is most recent that conform to semver, maintainers of the project can be locked into older versions, unable to reproduce possible issues before making a release.

Please remove the file and gitignore it.

**Comment by maltsev** [comment]
Thank you for explaining that! 

> maintainers of the project can be locked into older versions

I suppose it's fine to not issue a new release with this fix then?

**Comment by stevenvachon** [comment]
No prob.

> I suppose it's fine to not issue a new release with this fix then?

Yep, should be fine as a git commit as it only affects maintainers.
