### ISSUE TITLE
Fix ES6+ minification

### ISSUE THREAD

**Issue by elgs** [posthtml/htmlnano#48]
Would you please take a look at this issue? Thanks!

https://github.com/parcel-bundler/parcel/issues/1173

**Comment by maltsev** [comment]
Thanks for submitting the bug! I published new version 0.1.8 with the fix.

It was an issue with `uglify-js`, which is used internally to minify JS. It turned out that it doesn't support ES6+ minification. So I replaced it with `uglify-es` and now it seems to be working fine.

**Comment by elgs** [comment]
Thank you, @maltsev!
