### ISSUE TITLE
Add a safe preset

### ISSUE THREAD

**Issue by DeMoorJasper** [posthtml/htmlnano#50]
It would be nice to have an option called `safe` that sets the optimal preset for minifying html safely, without having to thinker around untill you get a universal htmlnano config that works safe for everyone.

This idea came from trying to optimise the universal config for parcel, as we from time to time get a bug report with an unsafe transform.

If there is intrest for this feature but no available time, I'd love to implement this

**Comment by maltsev** [comment]
Hi @DeMoorJasper,

I'm definitely interested in making _htmlnano_ minifications safe by default for all types of HTML. Actually, I think we don't need a preset for that. All modules should minify code without breaking it by default. That was also my intention initially. And if someone wants to minify their code even more they could enable some hard-minifying options (in such case a preset you suggested would come in handy).

So I think we should solve that issue by changing the default modules config. Your help would be really appreciated, as, unfortunately, I don't have time right now for that. How does that sound to you?

**Comment by DeMoorJasper** [comment]
Awesome! I'll do a PR in a bit

**Comment by maltsev** [comment]
@DeMoorJasper thanks for making the default minification options even safer! I published [new version 0.1.9](https://github.com/posthtml/htmlnano/releases/tag/0.1.9).
