### ISSUE TITLE
Specify which SVGO plugins to use

### ISSUE THREAD

**Issue by hacknug** [posthtml/htmlnano#53]
Is there any way to enable/disable specific SVGO plugins using the config file? Right now my `.htmlnanorc` looks like this:

```json
{
    "minifySvg": false
}
```

And I'd like to have something like this:

```json
{
    "minifySvg": {
        "plugins": [
            { "removeViewBox": false }
        ]
    }
}
```

**Comment by maltsev** [comment]
htmlnano doesn't support `.htmlnanorc` yet. But you can configure SVGO plugins the following way:
```js
var htmlnano = require('htmlnano');
var options = {
    minifySvg: {
        plugins: [
            { convertColors: false }
        ]
    } 
};

var svg = '...';

htmlnano
    .process(svg, options)
    .then(function (result) {
        console.log(result.html);
    });
```

**Comment by hacknug** [comment]
Just fyi (in case you didn't know already), Parcel allows you to use such `.htmlnanorc` so maybe it would be a good idea to do something about it. I don't know much about the project but I can help if you're interested in doing something about it.

Since it seems like this is something related to parcel (at least for now), I'll open an issue there to discuss how this should be done so that file allows users to enable/disable just some of the plugins.

Thanks!

**Comment by maltsev** [comment]
> I don't know much about the project but I can help if you're interested in doing something about it.

I'm definitely interested and I'll appreciate your help! Though, I don't have spare time right now to implement that myself, but I'll accept your PR.
