### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by fstanis** [posthtml/htmlnano#57]
I'm experimenting with using PostHTML and htmlnano with a page I've built using [AMP](https://www.ampproject.org/) and, while it works fine right now (as AMP is just HTML), I think there are some minor tweaks to htmlnano that would make it even more useful.

Notably:

- AMP has some additional attributes that could be added to `collapseBooleanAttributes`, such as `amp`, `amp-custom`, `amp-boilerplate`.
- `mergeStyles` and `minifyCss` should ignore the AMP boilerplate (`<style amp-boilerplate>...</style>`).
- `amp-custom` should be preserved on the merged `<style>` tags, if present (maybe just include this in `styleKey`).
- There may be additional attributes to be added to `removeRedundantAttributes` and `removeEmptyAttributes` (still looking into this).

I'm happy to send a PR with these changes, but wanted to start some discussion first. Would you be OK with accepting these additions to htmlnano?

**Comment by maltsev** [comment]
> Would you be OK with accepting these additions to htmlnano?

Totally! I'll appreaciate it if you implement these minifications.

**Comment by fstanis** [comment]
#59 adds some of the things mentioned. I'll still need to look into whether additions can be made to `removeRedundantAttributes` and `removeEmptyAttributes`, but this should make htmlnano a lot more useful for AMP pages already.

**Comment by maltsev** [comment]
Great! 

@fstanis are you going to submit new PRs this week (except #60)? If yes then I'll wait for your new PRs before releasing a new htmlnano version. Otherwise I'll release it as soon as #60 gets merged.

**Comment by fstanis** [comment]
I think I'll close this for now. It seems AMP support is in a good place now based on my testing - if we missed something, it's easy to reopen.
