### ISSUE TITLE
HTML `visible="false"` gets minified to `visible` with no assigned value

### ISSUE THREAD

**Issue by dsinni** [posthtml/htmlnano#62]
I'm using ParcelJS `1.9.7` with htmlnano to bundle my A-Frame/WebVR/XR apps, and I've noticed some weird behavior with my apps after bundling the production build.

I discovered that this is because `visible="false"` in HTML is getting minified to `visible` with no assigned value, rendering the attribute ineffective. `visible` is a valid attribute for A-Frame, so I need it to get minified with the correct value.

I've tried overriding the documented options in `.htmlnanorc`, but none of them seems to fix the issue.

How can I avoid this? Any help would be appreciated.

Thanks.

**Comment by maltsev** [comment]
Thanks for submitting the bug report!

While I'm trying to figure out how to fix it I'd suggest you disabling the following minification in your config until the fix will be released:
```js
collapseBooleanAttributes: false
```

> I've tried overriding the documented options in .htmlnanorc

`htmlnano` doesn't support `.htmlnanorc` yet. I've opened issue #63 for implementing it.

**Comment by dsinni** [comment]
Thanks, @maltsev! That did the trick, at least until you release a more robust solution, if necessary.

I didn't see `collapseBooleanAttributes` in the documentation, however. Am I missing something?

> htmlnano doesn't support .htmlnanorc yet. I've opened issue #63 for implementing it.

That's odd, because it's actually working for me. I'm using Parcel, but it worked automatically after installing `htmlnano` `0.1.10` as a dev dependency. Maybe it's actually Parcel that supports `.htmlnanorc`?

**Comment by maltsev** [comment]
> I didn't see collapseBooleanAttributes in the documentation, however. Am I missing something?

Seems like you are :-) Here is [the link to that section](https://github.com/posthtml/htmlnano#collapsebooleanattributes).

**Comment by dsinni** [comment]
Ah, not sure how I missed that. Thanks, @maltsev!

**Comment by maltsev** [comment]
The bug has been fixed. The fix will be released in 0.2.0 version (I think next week).

**Comment by maltsev** [comment]
Released: [0.2.0](https://github.com/posthtml/htmlnano/releases/tag/0.2.0).

**Comment by dsinni** [comment]
Awesome! Thanks, @maltsev!

Was the issue specific to `visible`, or may other attributes have the same issue? If so, does this fix that as well?

Thanks again.

**Comment by maltsev** [comment]
> Was the issue specific to visible, or may other attributes have the same issue?

I checked the A-Frame docs and it seems that `visible` is the only attribute the module collapses. No there shouldn't be any other issues with this module.

**Comment by dsinni** [comment]
Excellent! Thank you, sir.

When do you expect the new release will be available via npm?

**Comment by dsinni** [comment]
Scratch that last comment. Got confused with Parcel for a second. Thanks for everything!
