### ISSUE TITLE
Inline scripts get reordered after minification

### ISSUE THREAD

**Issue by snippetkid** [posthtml/htmlnano#72]
Inline scripts in `<head>` are getting pushed to `<body>` after minification which apparently breaks the intended order. I am using parcel-bundler 1.12.2 with htmlnano 0.2.2

**Comment by maltsev** [comment]
Can you please post an example, where such merge breaks the page? Since all scripts are merged in the same order as they're present on the page, it should break nothing, I guess.

**Comment by maltsev** [comment]
To avoid such merge, I'd suggest adding the same class to all `<script>` in `<head>`, so they would be merged into the latest `<script>` tag in `<head>`. 

Or just disable `mergeScripts` module.

**Comment by maltsev** [comment]
I'm closing this issue. Feel free to re-open it if you still have this bug.
