### ISSUE TITLE
Upgrade to "uncss": "^0.17.0"

### ISSUE THREAD

**Issue by sqrter** [posthtml/htmlnano#74]

**Comment by maltsev** [comment]
Usually, I update all dependencies right before releasing a new version.

Does _uncss 0.17.0_ have some new features that worth releasing a new version earlier? If so, can you please re-open this issue post them here?

**Comment by sqrter** [comment]
Hi @maltsev, thank's for the quick response! I'm using htmlnano along with its "removeUnusedCss" module and it's really awesome. However, in my case, I must tell uncss to not process external scripts in my html. The latest uncss allows passing the needed option to jsdom that is used behind the scenes.

You can have a look at the release notes of uncss here https://github.com/uncss/uncss/releases/tag/0.17.0

Just let me know if I could help with preparing a pull request :)

**Comment by maltsev** [comment]
> Just let me know if I could help with preparing a pull request :)
No need :-) I just updated this and other dependencies. 

> it can definitely wait for some more meaningful release.
Great! Then I will not release a new version just with these changes.
