### ISSUE TITLE
remove crossorigin from boolean attribute list

### ISSUE THREAD

**Issue by Oloompa** [posthtml/htmlnano#78]
```html
<link rel="manifest" href="/app.webmanifest" crossorigin="use-credentials">
```

is converted by htmlnano in
```html
<link rel="manifest" href="/app.webmanifest" crossorigin="">
```

Adding `"collapseBooleanAttributes": false` to `.htmlnanorc` solved my issue.

But `crossorigin` is not a boolean attribute.

`crossorigin="use-credentials"` is required for website behind credentials, even if file is in same origin.

source: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes#Example_Webmanifest_with_credentials

**Comment by maltsev** [comment]
I published @fstanis fix as the version [0.2.4](https://github.com/posthtml/htmlnano/releases/tag/0.2.4).
