### ISSUE TITLE
Sorting attributes and classes for better gzipping

### ISSUE THREAD

**Issue by MathGeniusJodie** [posthtml/htmlnano#86]
right now I'm using "posthtml-attrs-sorter", considering making my own plugin for class names, figured it should probably be rolled into a minifier, the difference is pretty substantial, about 1-2% smaller in my testing

**Comment by maltsev** [comment]
That'd be awesome!

Yes, I think it's better to implement it as `htmlnano` module, so it can sort all things (e.g., attributes, class names, meta tags, etc).

**Comment by SukkaW** [comment]
@MathGeniusJodie Sorting based on alphabetical order has been implemented in #95 and supposed to be landed in the new version.

Sorting based on frequency will be implemented in the future (probably by me as well).
