### ISSUE TITLE
The most honest benchmarks in the world?

### ISSUE THREAD

**Issue by frederikhors** [posthtml/htmlnano#87]
Did I get it wrong or in the Readme it says that [html-minifier](https://www.npmjs.com/package/html-minifier) is better than this (htmlnano)?

![image](https://user-images.githubusercontent.com/41120635/87472029-92f46f00-c61f-11ea-9156-b1ead8a55b47.png)

**Comment by maltsev** [comment]
Yes, that's right. I want to make an honest comparison so developers could choose the right tool based on their requirements. Also, this serves as a goal of how much htmlnano could be improved.

These benchmarks were quite outdated. I updated them:

![image](https://user-images.githubusercontent.com/923973/87518838-7260ff00-c689-11ea-825a-6e999473e3a3.png)
